# Generated by Django 5.1.6 on 2025-03-11 07:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('table_name', models.CharField(max_length=255)),
                ('deleted', models.CharField(db_default='0', default='0', max_length=1)),
            ],
            options={
                'db_table': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PageLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deleted', models.CharField(db_default='0', default='0', max_length=1)),
            ],
            options={
                'db_table': 'page_layouts',
            },
        ),
        migrations.CreateModel(
            name='PageList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.CharField(db_default='0', default='0', max_length=1)),
            ],
            options={
                'db_table': 'page_lists',
            },
        ),
        migrations.CreateModel(
            name='ObjectField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('deleted', models.CharField(db_default='0', default='0', max_length=1)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.object')),
            ],
            options={
                'db_table': 'object_fields',
            },
        ),
        migrations.CreateModel(
            name='PageLayoutField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('deleted', models.CharField(db_default='0', default='0', max_length=1)),
                ('object_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.objectfield')),
                ('page_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.pagelayout')),
            ],
            options={
                'db_table': 'page_layout_fields',
            },
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='page_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.pagelist'),
        ),
        migrations.CreateModel(
            name='PageListField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hidden', models.CharField(db_default='0', default='0', max_length=1)),
                ('type', models.CharField(max_length=255)),
                ('deleted', models.CharField(db_default='0', default='0', max_length=1)),
                ('object_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.objectfield')),
                ('page_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.pagelist')),
            ],
            options={
                'db_table': 'page_list_fields',
            },
        ),
    ]
