CREATE TABLE PAGE_LAYOUT_FIELDS (
    ID VARCHAR(32) PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
    LABEL VARCHAR(255) NOT NULL,
    PAGE_LAYOUT_ID VARCHAR(255) NOT NULL,
	OBJECT_FIELD_ID VARCHAR(255) NOT NULL,
	TYPE VARCHAR(255) NOT NULL,
    DELETED VARCHAR(1) NOT NULL DEFAULT '0',
    FOREIGN KEY (PAGE_LAYOUT_ID) REFERENCES PAGE_LAYOUTS(ID),
    FOREIGN KEY (OBJECT_FIELD_ID) REFERENCES OBJECT_FIELDS(ID)
);