CREATE TABLE OBJECT_FIELDS (
    ID VARCHAR(32) PRIMARY KEY,
    OBJECT_ID VARCHAR(32) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    LABEL VARCHAR(255) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    DELETED VARCHAR(1) NOT NULL DEFAULT '0',,
    FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS(ID)
);